services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network
    depends_on:
      - webapp
      - api
      - ml
    profiles: ["production"]

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
      args:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - PORT=8000
      - ML_SERVICE_URL=${ML_SERVICE_URL}
      - MONGO_URI=mongodb://root:example@mongodb:27017
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - mongodb

  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile
    environment:
      - PORT=8001
    ports:
      - "8001:8001"
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: